application:
  # The list of Debian packages to be installed on nodes where the
  # application deployment script runs.
  debian_packages:
    - python3-venv
  # The list of pip installable python packages to be installed into a
  # virtual environment on nodes where the application deployment
  # script runs.
  #
  # NOTE: currently none are known, the examples below show what this
  # might look like though... Each list of dependencies is normally
  # specific to and grouped by the name of a particular python script
  # that might be run as part of deployment and needs to be installed.
  python_deps: []
#    examples:
#      - daemonize~=2.5
#      - flask~=3.0
#      - requests~=2.32
